package br.com.eversee.app.appeversee.dao

//val DATABASE_NAME = "Siga"
//val COL_ID = "ID"
val COL_ID_OBRA = "ID_OBRA"
val COL_ULT_IMP = "ULT_IMP"
val COL_QT_REG_IMP = "QT_REG_IMP"
val COL_INI_IMP = "INI_IMP"
val COL_FIM_IMP = "FIM_IMP"
val COL_VERSAO = "VERSAO"
val COL_IDIOMA = "IDIOMA"
val COL_DADOS_CELULARES = "DADOS_CELULARES"
//"DADOS_CELULARES" INTEGER, "DADOS_CELULARES_BD" INTEGER, "DADOS_CELULARES_FOTOS" INTEGER, "DADOS_CELULARES_AUDIO" INTEGER, "DADOS_CELULARES_VIDEOS" INTEGER, "WIFI_BD" INTEGER, "WIFI_FOTOS" INTEGER, "WIFI_AUDIO" INTEGER, "WIFI_VIDEOS" INTEGER, "FORMATO_DATA" TEXT, "FORMATO_HORA" TEXT, "SEPARADOR_MILHAR" TEXT, "SEPARADOR_DECIMAL" TEXT, PRIMARY KEY("ID") )





class DataBaseConfigHandler {
}